---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: vault-promote
    image: "geerlingguy/docker-debian12-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: "$MOLECULE_PROJECT_DIRECTORY/.."
  inventory:
    host_vars:
      vault-promote:
        vault_host: 
          test_host: "secret_stuff"
        vault_all_group: 
          group_test_host: "group_secret_stuff"
        nginx_certbot_appname:
          nginx_certbot_domain_name: 'some.url'
          nginx_certbot_port: 8080
        vault_promote_no_log: false
        vault_promote_var_to_extract:
          nginx_certbot: "nginx_certbot_appname"
verifier:
  name: ansible
